POST http://localhost:9090/facultyPost
Content-Type: application/json

{
    "event_name":"Workshop",
    "event_title":"MERN Stack",
    "event_organizer":"Computer Science and Engineering",
    "event_sponsor":"IEI management",
    "event_date":00-00-0000,
    "event_venue":"Seminar hall II",
    "guest_name":"Mr. Razak Mohamed",
    "guest_designation":"Founder",
    "guest_address":"Salem",
    "guest_number":1234567890,
    "guest_email":"razak@gmail.com",
    "student_count":60,
    "faculty_count":3,
    "others_count":0,
    "event_photo_1":"photo1/path",
    "event_photo_2":"photo2/path",
    "event_po":"1,2,3,4",
    "proposal_date":'00-00-0000',
    "proposal_hod":'00-00-0000',
    "proposal_principal":'00-00-0000',
    "completion_date":'00-00-0000',
    "completion_hod":'00-00-0000',
    "completion_principal":'00-00-0000',
    "pdf":"pdf/path",
    "approval_status":0,
    "event_budget":40000,
    "event_coordinator":"Mr. Sridhar",
    "coordinator_phno":9874563210,
    "coordinator_designation":0,
    "event_duration":"9.00 - 4.00",
    "event_os":"Dr. Kavitha",
    "event_time":"9.00",
    "event_description":"About the event",
    "acdyr_id":0,
    "event_budget_utilized":50000,
    "dept_id":0,
    "sem_id":0
}