GET http://localhost:9090/facultyGet

GET http://localhost:9090/facultyGet

POST http://localhost:9090/facultyPost
Content-Type: application/json

{
    "sno":2,
    "event_name": 2,
    "event_title": "Full Stack",
    "event_organizer": "CSE",
    "event_sponsor": "IEI",
    "event_date": "1899-11-29T18:38:50.000Z",
    "event_venue": "Seminar hall II",
    "guest_name": "Razak",
    "guest_designation": "Founder",
    "guest_address": "Salem",
    "guest_number": 1234567890,
    "guest_email": "razak@gmail.com",
    "student_count": 60,
    "faculty_count": 3,
    "others_count": 0,
    "event_photo_1": "photo1/path",
    "event_photo_2": "photo2/path",
    "event_po": "1,2,3,4",
    "proposal_date": "1899-11-29T18:38:50.000Z",
    "proposal_hod": "1899-11-29T18:38:50.000Z",
    "proposal_principal": "1899-11-29T18:38:50.000Z",
    "completion_date": "1899-11-29T18:38:50.000Z",
    "completion_hod": "1899-11-29T18:38:50.000Z",
    "completion_principal": "1899-11-29T18:38:50.000Z",
    "pdf": "pdf/path",
    "approval_status": 0,
    "event_budget": 40000,
    "event_coordinator": "Mr. Sridhar",
    "coordinator_phno": 2147483647,
    "coordinator_designation": "0",
    "event_duration": "9.00 - 4.00",
    "event_os": "Dr. Kavitha",
    "event_time": "9.00",
    "event_description": "About the event",
    "acdyr_id": 0,
    "event_budget_utilized": 50000,
    "dept_id": 0,
    "sem_id": 0
}
